"""
Stage Artifact
==============

Represents the output produced by a workflow stage.

Every agent produces exactly one StageArtifact.

The artifact flows through the entire execution pipeline.

Lifecycle

Agent
    ↓
Reviewer
    ↓
Memory Extraction
    ↓
Execution Engine
    ↓
Workflow Engine

The artifact contains no execution logic.

It is a transport object only.
"""

from dataclasses import dataclass, field
from datetime import datetime


@dataclass(slots=True)
class StageArtifact:
    """
    Output generated by one workflow stage.
    """

    # ======================================================
    # Identity
    # ======================================================

    stage: str

    # ======================================================
    # Main Result
    # ======================================================

    content: str

    # ======================================================
    # Optional Structured Data
    # ======================================================

    document: str | None = None

    filename: str | None = None

    format: str = "markdown"

    # ======================================================
    # Metadata
    # ======================================================

    metadata: dict = field(default_factory=dict)

    # ======================================================
    # Generated Files
    # ======================================================

    files: list[str] = field(default_factory=list)

    # ======================================================
    # Runtime Information
    # ======================================================

    created_at: datetime = field(default_factory=datetime.utcnow)

    version: int = 1